### PR TITLE
Ignore gitignored files

### LINKED ISSUE #457: Large build contexts due to not respecting `.gitignore`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Trying to build a local directory with large folders like NodeJS `node_modules` or Rust `target` will take a long time, since Nixpacks will attempt to copy those folders into a tempdir and into the build container.

### To reproduce

Create a new Rust project
Run `cargo build` once locally
Run `nixpacks build .` and see how it takes a long time

### Expected behavior

Nixpacks would respect the `.gitignore` file and only copy the files that are needed.

### Environment

Windows 11
Nixpacks v0.3.8

### PR DESCRIPTION
**Pull request by Milo123459**
This PR ignores gitignored files. Fixes #457

### CODE REVIEW

File: src/nixpacks/app.rs [hunk 1]
```diff
@@ -74,11 +76,13 @@ impl App {
             None => return Ok(Vec::new()),
         };
 
-        let walker = WalkDir::new(&self.source);
+        let walker = WalkBuilder::new(&self.source)
+            .hidden(false)
```
Comment (coffee-cup) [inline src/nixpacks/app.rs:80]: This will not copy over hidden files right? I don't think that is the behaviour we want.

File: src/nixpacks/files.rs [hunk 2]
```diff
@@ -1,30 +1,34 @@
 use anyhow::Result;
+use ignore::WalkBuilder;
 use std::{fs, io, path::Path};
-use walkdir::WalkDir;
 
 pub fn recursive_copy_dir<T: AsRef<Path>, Q: AsRef<Path>>(source: T, dest: Q) -> Result<()> {
-    let walker = WalkDir::new(&source).follow_links(false);
+    let walker = WalkBuilder::new(&source)
+        .follow_links(false)
+        .hidden(false)
```
Comment (coffee-cup) [inline src/nixpacks/files.rs:8]: Same as here

File: src/nixpacks/app.rs (hunk 1 above)
Comment (Milo123459) [reply src/nixpacks/app.rs:80]: I think this actually disables ignoring hidden files. It's a stupid way of naming things basically.

Comment (coffee-cup) [reply src/nixpacks/app.rs:80]: Well that is confusing af 
image

Want to add a comment so it doesn't accidentally get removed in the future

**Review by coffee-cup — APPROVED** [review]
