### PR TITLE
Fix Django detection without requirements.txt

### LINKED ISSUE #384: NixPack does not detect Python when using pyproject.toml with poetry.lock
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As per nixpack docs, if pyproject.toml with poetry.lock exist, it will detect it as a Python project. But it still does not detect it unless a requirements.txt is added.

### To reproduce

steps to reproduce:
1. Create a python project using poetry (say a django project)
2. run `railway up`
3. Error shows up.

Project file structure
image

Error on `railway up` without requirements.txt
image

Logs in Railway Dashboard
```
==============
Using Nixpacks
==============
Nixpacks build failed
 
Error: Getting setup phase
 
Caused by:
No such file or directory (os error 2)
```

### Expected behavior

Project is detected to be of Python and gets deployed.

### Environment

railway

### PR DESCRIPTION
**Pull request by JakeCooper**
This PR fixes detection of Django without requirements.txt file. Fixes #384

### CODE REVIEW

File: src/providers/python.rs [hunk 1]
```diff
@@ -94,6 +95,7 @@ impl PythonProvider {
 
         pkgs.append(&mut vec![python_base_package]);
 
+        println!("Let frat");
```
Comment (coffee-cup) [inline src/providers/python.rs:98]: 🔫

**Review by coffee-cup — APPROVED** [review]
