### PR TITLE
PNPM fixes

### LINKED ISSUE #702: PNPM Cache Location is incorrect
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Nixpacks attempts to cache `/root/.cache/pnpm`, but this is incorrect

### To reproduce

_No response_

### Expected behavior

The correct store directory is `/root/.local/share/pnpm/store/v3`

### Environment

Railway - Nixpacks 0.15.0

### PR DESCRIPTION
**Pull request by Milo123459**
This PR fixes the PNPM cache directory and the way NX apps are started with PNPM. This also contains some general nx fixes which swaps from using `npx` always to the package manager dlx command.

Fixes #702, #701

### CODE REVIEW

File: src/providers/node/nx.rs [hunk 1]
```diff
@@ -106,10 +111,16 @@ impl Nx {
             if let Some(start_target) = project_json.targets.start {
                 if let Some(configurations) = start_target.configurations {
                     if configurations.production.is_some() {
-                        return Ok(Some(format!("npx nx run {nx_app_name}:start:production")));
+                        return Ok(Some(format!(
+                            "{} nx run {nx_app_name}:start:production",
+                            NodeProvider::get_package_manager_dlx_command(app)
```
Comment (coffee-cup) [inline src/providers/node/nx.rs:116]: This is fine for now, but we likely want to refactor the Node provider soon since this creates a circular dependency. Node -> Nx -> Node

**Review by coffee-cup — APPROVED** [review]
