### PR TITLE
copy files manually rather than invoking cp

### LINKED ISSUE #98: `build` fails on Windows, due to `cp` not existing
The `cp` shell command is not available on Windows, therefore building fails when the program attempts to copy source files into a temporary directory.

### PR DESCRIPTION
**Pull request by nebulatgs**
Fixes the `build` command on Windows by manually copying files rather than using UNIX shell commands.

Fixes #98

### CODE REVIEW

File: src/nixpacks/mod.rs [hunk 1]
```diff
@@ -138,27 +139,43 @@ impl<'a> AppBuilder<'a> {
...
-        if !copy_result.success() {
-            bail!("Copy failed")
+        let in_dir = PathBuf::from(source);
+
+        let walker = WalkDir::new(&in_dir).follow_links(true);
+        for entry in walker {
+            let entry = entry?;
+
+            let from = entry.path();
+            dbg!(&from, &dir, &in_dir);
```
Comment (coffee-cup) [inline src/nixpacks/mod.rs:160]: 🔫  (remove this line)

File: src/nixpacks/mod.rs [hunk 2]
```diff
@@ -138,27 +139,43 @@ impl<'a> AppBuilder<'a> {
...
-            .arg("-a")
-            .arg(format!("{}/.", source))
-            .arg(dir.clone())
-            .spawn()?;
-        let copy_result = copy_cmd.wait().context("Copying app source to tmp dir")?;
-        if !copy_result.success() {
-            bail!("Copy failed")
+        let in_dir = PathBuf::from(source);
+
+        let walker = WalkDir::new(&in_dir).follow_links(true);
```
Comment (coffee-cup) [inline src/nixpacks/mod.rs:155]: I think this should be moved out into a function

File: src/nixpacks/mod.rs (hunk 1 above)
Comment (nebulatgs) [reply src/nixpacks/mod.rs:160]: 😨

**Review by coffee-cup — APPROVED** [review]
